package com.edalac.modelo.dto;
// default package
// Generated 14/11/2016 09:15:43 AM by Hibernate Tools 3.5.0.Final

/**
 * TbArticulo generated by hbm2java
 */
public class TbArticulo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private long nbIdarticulo;
	private TbEmpresa tbEmpresa;
	private String vrCodigoArticulo;
	private String vrDescripcion;
	private Long nbCantidad;
	private Long nbStockminimo;
	private Long nbStockmaximo;
	private Boolean nbEstado;

	public TbArticulo() {
	}

	public TbArticulo(long nbIdarticulo, String vrCodigoArticulo) {
		this.nbIdarticulo = nbIdarticulo;
		this.vrCodigoArticulo = vrCodigoArticulo;
	}


	public long getNbIdarticulo() {
		return this.nbIdarticulo;
	}

	public void setNbIdarticulo(long nbIdarticulo) {
		this.nbIdarticulo = nbIdarticulo;
	}

	public TbEmpresa getTbEmpresa() {
		return this.tbEmpresa;
	}

	public void setTbEmpresa(TbEmpresa tbEmpresa) {
		this.tbEmpresa = tbEmpresa;
	}

	public String getVrCodigoArticulo() {
		return this.vrCodigoArticulo;
	}

	public void setVrCodigoArticulo(String vrCodigoArticulo) {
		this.vrCodigoArticulo = vrCodigoArticulo;
	}

	public String getVrDescripcion() {
		return this.vrDescripcion;
	}

	public void setVrDescripcion(String vrDescripcion) {
		this.vrDescripcion = vrDescripcion;
	}

	public Long getNbCantidad() {
		return this.nbCantidad;
	}

	public void setNbCantidad(Long nbCantidad) {
		this.nbCantidad = nbCantidad;
	}

	public Long getNbStockminimo() {
		return this.nbStockminimo;
	}

	public void setNbStockminimo(Long nbStockminimo) {
		this.nbStockminimo = nbStockminimo;
	}

	public Long getNbStockmaximo() {
		return this.nbStockmaximo;
	}

	public void setNbStockmaximo(Long nbStockmaximo) {
		this.nbStockmaximo = nbStockmaximo;
	}

	public Boolean getNbEstado() {
		return this.nbEstado;
	}

	public void setNbEstado(Boolean nbEstado) {
		this.nbEstado = nbEstado;
	}

	
}
