package com.edalac.modelo.dto;
/**
 * TbCiudad generated by hbm2java
 */
public class TbCiudad implements java.io.Serializable {

	private static final long serialVersionUID = -7911550500712043671L;
	private long nbIdciudad;
	private TbDepartamento tbDepartamento;
	private String vrNombre;

	public TbCiudad() {
	}

	public TbCiudad(long nbIdciudad, TbDepartamento tbDepartamento, String vrNombre) {
		this.nbIdciudad = nbIdciudad;
		this.tbDepartamento = tbDepartamento;
		this.vrNombre = vrNombre;
	}

	public long getNbIdciudad() {
		return this.nbIdciudad;
	}

	public void setNbIdciudad(long nbIdciudad) {
		this.nbIdciudad = nbIdciudad;
	}

	public TbDepartamento getTbDepartamento() {
		return this.tbDepartamento;
	}

	public void setTbDepartamento(TbDepartamento tbDepartamento) {
		this.tbDepartamento = tbDepartamento;
	}

	public String getVrNombre() {
		return this.vrNombre;
	}

	public void setVrNombre(String vrNombre) {
		this.vrNombre = vrNombre;
	}
}
