package com.edalac.modelo.dto;

/**
 * TbDepartamento generated by hbm2java
 */
public class TbDepartamento implements java.io.Serializable {

	private static final long serialVersionUID = -4294955149842120529L;
	private long nbIddepartamento;
	private TbPais tbPais;
	private String vrNombre;

	public TbDepartamento() {
	}

	public TbDepartamento(long nbIddepartamento, TbPais tbPais, String vrNombre) {
		this.nbIddepartamento = nbIddepartamento;
		this.tbPais = tbPais;
		this.vrNombre = vrNombre;
	}

	public long getNbIddepartamento() {
		return this.nbIddepartamento;
	}

	public void setNbIddepartamento(long nbIddepartamento) {
		this.nbIddepartamento = nbIddepartamento;
	}

	public TbPais getTbPais() {
		return this.tbPais;
	}

	public void setTbPais(TbPais tbPais) {
		this.tbPais = tbPais;
	}

	public String getVrNombre() {
		return this.vrNombre;
	}

	public void setVrNombre(String vrNombre) {
		this.vrNombre = vrNombre;
	}
}
