package com.edalac.modelo.dto;
// default package
// Generated 14/11/2016 09:15:43 AM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;

/**
 * TbDetalleFactura generated by hbm2java
 */
public class TbDetalleFactura implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private long nbIdDetalle;
	private TbFactura tbFactura;
	private TbArticulo tbArticulo;
	private Integer nbCantidad;
	private BigDecimal nbValorUnitario;
	private BigDecimal nbValorIva;
	private BigDecimal nbValorDescuento;

	public TbDetalleFactura() {
	}

	public TbDetalleFactura(long nbIdDetalle) {
		this.nbIdDetalle = nbIdDetalle;
	}

	public TbDetalleFactura(long nbIdDetalle, TbFactura tbFactura, TbArticulo tbArticulo, Integer nbCantidad,
			BigDecimal nbValorUnitario, BigDecimal nbValorIva, BigDecimal nbValorDescuento) {
		this.nbIdDetalle = nbIdDetalle;
		this.tbFactura = tbFactura;
		this.tbArticulo = tbArticulo;
		this.nbCantidad = nbCantidad;
		this.nbValorUnitario = nbValorUnitario;
		this.nbValorIva = nbValorIva;
		this.nbValorDescuento = nbValorDescuento;
	}

	public long getNbIdDetalle() {
		return this.nbIdDetalle;
	}

	public void setNbIdDetalle(long nbIdDetalle) {
		this.nbIdDetalle = nbIdDetalle;
	}

	public TbFactura getTbFactura() {
		return this.tbFactura;
	}

	public void setTbFactura(TbFactura tbFactura) {
		this.tbFactura = tbFactura;
	}

	public TbArticulo getTbArticulo() {
		return this.tbArticulo;
	}

	public void setTbArticulo(TbArticulo tbArticulo) {
		this.tbArticulo = tbArticulo;
	}

	public Integer getNbCantidad() {
		return this.nbCantidad;
	}

	public void setNbCantidad(Integer nbCantidad) {
		this.nbCantidad = nbCantidad;
	}

	public BigDecimal getNbValorUnitario() {
		return this.nbValorUnitario;
	}

	public void setNbValorUnitario(BigDecimal nbValorUnitario) {
		this.nbValorUnitario = nbValorUnitario;
	}

	public BigDecimal getNbValorIva() {
		return this.nbValorIva;
	}

	public void setNbValorIva(BigDecimal nbValorIva) {
		this.nbValorIva = nbValorIva;
	}

	public BigDecimal getNbValorDescuento() {
		return this.nbValorDescuento;
	}

	public void setNbValorDescuento(BigDecimal nbValorDescuento) {
		this.nbValorDescuento = nbValorDescuento;
	}

}
