package com.edalac.modelo.dto;
// default package
// Generated 14/11/2016 09:15:43 AM by Hibernate Tools 3.5.0.Final

/**
 * TbDepartamento generated by hbm2java
 */
public class TbDepartamento implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private long nbIddepartamento;
	private TbPais tbPais;
	private String vrNombre;

	public TbDepartamento() {
	}

	public TbDepartamento(long nbIddepartamento, TbPais tbPais, String vrNombre) {
		this.nbIddepartamento = nbIddepartamento;
		this.tbPais = tbPais;
		this.vrNombre = vrNombre;
	}

	public long getNbIddepartamento() {
		return this.nbIddepartamento;
	}

	public void setNbIddepartamento(long nbIddepartamento) {
		this.nbIddepartamento = nbIddepartamento;
	}

	public TbPais getTbPais() {
		return this.tbPais;
	}

	public void setTbPais(TbPais tbPais) {
		this.tbPais = tbPais;
	}

	public String getVrNombre() {
		return this.vrNombre;
	}

	public void setVrNombre(String vrNombre) {
		this.vrNombre = vrNombre;
	}

}
