package com.edalac.modelo.dto;
// default package
// Generated 14/11/2016 09:15:43 AM by Hibernate Tools 3.5.0.Final

/**
 * TbEmpresa generated by hbm2java
 */
public class TbEmpresa implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private long nbIdempresa;
	private String vrNombreEmpresa;
	private String vrCodigoEmpresa;

	public TbEmpresa() {
	}

	public TbEmpresa(long nbIdempresa) {
		this.nbIdempresa = nbIdempresa;
	}

	
	public long getNbIdempresa() {
		return this.nbIdempresa;
	}

	public void setNbIdempresa(long nbIdempresa) {
		this.nbIdempresa = nbIdempresa;
	}

	public String getVrNombreEmpresa() {
		return this.vrNombreEmpresa;
	}

	public void setVrNombreEmpresa(String vrNombreEmpresa) {
		this.vrNombreEmpresa = vrNombreEmpresa;
	}

	public String getVrCodigoEmpresa() {
		return this.vrCodigoEmpresa;
	}

	public void setVrCodigoEmpresa(String vrCodigoEmpresa) {
		this.vrCodigoEmpresa = vrCodigoEmpresa;
	}

}
