package com.edalac.modelo.dto;
// default package
// Generated 19/04/2017 11:44:33 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TbEmpresa generated by hbm2java
 */
public class TbEmpresa implements java.io.Serializable {

	private long nbIdempresa;
	private String vrNombreEmpresa;
	private String vrCodigoEmpresa;
	private Set tbFacturas = new HashSet(0);
	private Set tbUsuarios = new HashSet(0);
	private Set tbArticulos = new HashSet(0);

	public TbEmpresa() {
	}

	public TbEmpresa(long nbIdempresa) {
		this.nbIdempresa = nbIdempresa;
	}

	public TbEmpresa(long nbIdempresa, String vrNombreEmpresa, String vrCodigoEmpresa, Set tbFacturas, Set tbUsuarios,
			Set tbArticulos) {
		this.nbIdempresa = nbIdempresa;
		this.vrNombreEmpresa = vrNombreEmpresa;
		this.vrCodigoEmpresa = vrCodigoEmpresa;
		this.tbFacturas = tbFacturas;
		this.tbUsuarios = tbUsuarios;
		this.tbArticulos = tbArticulos;
	}

	public long getNbIdempresa() {
		return this.nbIdempresa;
	}

	public void setNbIdempresa(long nbIdempresa) {
		this.nbIdempresa = nbIdempresa;
	}

	public String getVrNombreEmpresa() {
		return this.vrNombreEmpresa;
	}

	public void setVrNombreEmpresa(String vrNombreEmpresa) {
		this.vrNombreEmpresa = vrNombreEmpresa;
	}

	public String getVrCodigoEmpresa() {
		return this.vrCodigoEmpresa;
	}

	public void setVrCodigoEmpresa(String vrCodigoEmpresa) {
		this.vrCodigoEmpresa = vrCodigoEmpresa;
	}

	public Set getTbFacturas() {
		return this.tbFacturas;
	}

	public void setTbFacturas(Set tbFacturas) {
		this.tbFacturas = tbFacturas;
	}

	public Set getTbUsuarios() {
		return this.tbUsuarios;
	}

	public void setTbUsuarios(Set tbUsuarios) {
		this.tbUsuarios = tbUsuarios;
	}

	public Set getTbArticulos() {
		return this.tbArticulos;
	}

	public void setTbArticulos(Set tbArticulos) {
		this.tbArticulos = tbArticulos;
	}

}
