package com.edalac.modelo.dto;

/**
 * TbEstado generated by hbm2java
 */
public class TbEstado implements java.io.Serializable {

	private static final long serialVersionUID = -8145316788107517870L;
	private long nbIdestado;
	private String vrDescripcion;

	public TbEstado() {
	}

	public TbEstado(long nbIdestado, String vrDescripcion) {
		this.nbIdestado = nbIdestado;
		this.vrDescripcion = vrDescripcion;
	}

	public long getNbIdestado() {
		return this.nbIdestado;
	}

	public void setNbIdestado(long nbIdestado) {
		this.nbIdestado = nbIdestado;
	}

	public String getVrDescripcion() {
		return this.vrDescripcion;
	}

	public void setVrDescripcion(String vrDescripcion) {
		this.vrDescripcion = vrDescripcion;
	}
}
