package com.edalac.modelo.dto;
// default package
// Generated 19/04/2017 11:44:33 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TbFactura generated by hbm2java
 */
public class TbFactura implements java.io.Serializable {

	private long nbIdFactura;
	private TbTercero tbTercero;
	private TbEmpresa tbEmpresa;
	private String vrNumeroFactura;
	private String dtFechaFactura;
	private String vrDescripcion;
	private BigDecimal nbValorTotal;
	private Long nbVendedor;
	private String vrTipoFactura;
	private Character vrEstadoFactura;
	private Set tbDetalleFacturas = new HashSet(0);

	public TbFactura() {
	}

	public TbFactura(long nbIdFactura) {
		this.nbIdFactura = nbIdFactura;
	}

	public TbFactura(long nbIdFactura, TbTercero tbTercero, TbEmpresa tbEmpresa, String vrNumeroFactura,
			String dtFechaFactura, String vrDescripcion, BigDecimal nbValorTotal, Long nbVendedor, String vrTipoFactura,
			Character vrEstadoFactura, Set tbDetalleFacturas) {
		this.nbIdFactura = nbIdFactura;
		this.tbTercero = tbTercero;
		this.tbEmpresa = tbEmpresa;
		this.vrNumeroFactura = vrNumeroFactura;
		this.dtFechaFactura = dtFechaFactura;
		this.vrDescripcion = vrDescripcion;
		this.nbValorTotal = nbValorTotal;
		this.nbVendedor = nbVendedor;
		this.vrTipoFactura = vrTipoFactura;
		this.vrEstadoFactura = vrEstadoFactura;
		this.tbDetalleFacturas = tbDetalleFacturas;
	}

	public long getNbIdFactura() {
		return this.nbIdFactura;
	}

	public void setNbIdFactura(long nbIdFactura) {
		this.nbIdFactura = nbIdFactura;
	}

	public TbTercero getTbTercero() {
		return this.tbTercero;
	}

	public void setTbTercero(TbTercero tbTercero) {
		this.tbTercero = tbTercero;
	}

	public TbEmpresa getTbEmpresa() {
		return this.tbEmpresa;
	}

	public void setTbEmpresa(TbEmpresa tbEmpresa) {
		this.tbEmpresa = tbEmpresa;
	}

	public String getVrNumeroFactura() {
		return this.vrNumeroFactura;
	}

	public void setVrNumeroFactura(String vrNumeroFactura) {
		this.vrNumeroFactura = vrNumeroFactura;
	}

	public String getDtFechaFactura() {
		return this.dtFechaFactura;
	}

	public void setDtFechaFactura(String dtFechaFactura) {
		this.dtFechaFactura = dtFechaFactura;
	}

	public String getVrDescripcion() {
		return this.vrDescripcion;
	}

	public void setVrDescripcion(String vrDescripcion) {
		this.vrDescripcion = vrDescripcion;
	}

	public BigDecimal getNbValorTotal() {
		return this.nbValorTotal;
	}

	public void setNbValorTotal(BigDecimal nbValorTotal) {
		this.nbValorTotal = nbValorTotal;
	}

	public Long getNbVendedor() {
		return this.nbVendedor;
	}

	public void setNbVendedor(Long nbVendedor) {
		this.nbVendedor = nbVendedor;
	}

	public String getVrTipoFactura() {
		return this.vrTipoFactura;
	}

	public void setVrTipoFactura(String vrTipoFactura) {
		this.vrTipoFactura = vrTipoFactura;
	}

	public Character getVrEstadoFactura() {
		return this.vrEstadoFactura;
	}

	public void setVrEstadoFactura(Character vrEstadoFactura) {
		this.vrEstadoFactura = vrEstadoFactura;
	}

	public Set getTbDetalleFacturas() {
		return this.tbDetalleFacturas;
	}

	public void setTbDetalleFacturas(Set tbDetalleFacturas) {
		this.tbDetalleFacturas = tbDetalleFacturas;
	}

}
