package com.edalac.modelo.dto;
// Generated 19/04/2017 11:44:33 PM by Hibernate Tools 3.5.0.Final

/**
 * TbPais generated by hbm2java
 */
public class TbPais implements java.io.Serializable {

	private static final long serialVersionUID = 576566018594488275L;
	private long nbIdpais;
	private String vrNombre;

	public TbPais() {
	}

	public TbPais(long nbIdpais, String vrNombre) {
		this.nbIdpais = nbIdpais;
		this.vrNombre = vrNombre;
	}

	public long getNbIdpais() {
		return this.nbIdpais;
	}

	public void setNbIdpais(long nbIdpais) {
		this.nbIdpais = nbIdpais;
	}

	public String getVrNombre() {
		return this.vrNombre;
	}

	public void setVrNombre(String vrNombre) {
		this.vrNombre = vrNombre;
	}

}
