package com.edalac.modelo.dto;

/**
 * TbRol generated by hbm2java
 */
public class TbRol implements java.io.Serializable {

	private static final long serialVersionUID = -975142508061293082L;
	private long nbIdRol;
	private String vrDescripcion;
	private String vrAlias;

	public TbRol() {
	}

	public TbRol(long nbIdRol) {
		this.nbIdRol = nbIdRol;
	}

	public long getNbIdRol() {
		return this.nbIdRol;
	}

	public void setNbIdRol(long nbIdRol) {
		this.nbIdRol = nbIdRol;
	}

	public String getVrDescripcion() {
		return this.vrDescripcion;
	}

	public void setVrDescripcion(String vrDescripcion) {
		this.vrDescripcion = vrDescripcion;
	}

	public String getVrAlias() {
		return this.vrAlias;
	}

	public void setVrAlias(String vrAlias) {
		this.vrAlias = vrAlias;
	}

}
