package com.edalac.modelo.dto;
// default package
// Generated 14/11/2016 09:15:43 AM by Hibernate Tools 3.5.0.Final

/**
 * TbTercero generated by hbm2java
 */
public class TbTercero implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private long nbIdpersona;
	private TbCiudad tbCiudad;
	private TbTipopersona tbTipopersona;
	private TbTipodocumento tbTipodocumento;
	private TbEstado tbEstado;
	private String vrApellidos;
	private String vrNombres;
	private String vrRazonSocial;
	private String vrDireccion;
	private String vrEmail;
	private Long nbNit;
	private Integer nbDigitoverificacion;
	private String vrTelefono;

	public TbTercero() {
	}

	public TbTercero(long nbIdpersona, TbCiudad tbCiudad, TbTipopersona tbTipopersona, TbTipodocumento tbTipodocumento,
			TbEstado tbEstado, String vrNombres) {
		this.nbIdpersona = nbIdpersona;
		this.tbCiudad = tbCiudad;
		this.tbTipopersona = tbTipopersona;
		this.tbTipodocumento = tbTipodocumento;
		this.tbEstado = tbEstado;
		this.vrNombres = vrNombres;
	}

	public long getNbIdpersona() {
		return this.nbIdpersona;
	}

	public void setNbIdpersona(long nbIdpersona) {
		this.nbIdpersona = nbIdpersona;
	}

	public TbCiudad getTbCiudad() {
		return this.tbCiudad;
	}

	public void setTbCiudad(TbCiudad tbCiudad) {
		this.tbCiudad = tbCiudad;
	}

	public TbTipopersona getTbTipopersona() {
		return this.tbTipopersona;
	}

	public void setTbTipopersona(TbTipopersona tbTipopersona) {
		this.tbTipopersona = tbTipopersona;
	}

	public TbTipodocumento getTbTipodocumento() {
		return this.tbTipodocumento;
	}

	public void setTbTipodocumento(TbTipodocumento tbTipodocumento) {
		this.tbTipodocumento = tbTipodocumento;
	}

	public TbEstado getTbEstado() {
		return this.tbEstado;
	}

	public void setTbEstado(TbEstado tbEstado) {
		this.tbEstado = tbEstado;
	}

	public String getVrApellidos() {
		return this.vrApellidos;
	}

	public void setVrApellidos(String vrApellidos) {
		this.vrApellidos = vrApellidos;
	}

	public String getVrNombres() {
		return this.vrNombres;
	}

	public void setVrNombres(String vrNombres) {
		this.vrNombres = vrNombres;
	}

	public String getVrRazonSocial() {
		return this.vrRazonSocial;
	}

	public void setVrRazonSocial(String vrRazonSocial) {
		this.vrRazonSocial = vrRazonSocial;
	}

	public String getVrDireccion() {
		return this.vrDireccion;
	}

	public void setVrDireccion(String vrDireccion) {
		this.vrDireccion = vrDireccion;
	}

	public String getVrEmail() {
		return this.vrEmail;
	}

	public void setVrEmail(String vrEmail) {
		this.vrEmail = vrEmail;
	}

	public Long getNbNit() {
		return this.nbNit;
	}

	public void setNbNit(Long nbNit) {
		this.nbNit = nbNit;
	}

	public Integer getNbDigitoverificacion() {
		return this.nbDigitoverificacion;
	}

	public void setNbDigitoverificacion(Integer nbDigitoverificacion) {
		this.nbDigitoverificacion = nbDigitoverificacion;
	}

	public String getVrTelefono() {
		return this.vrTelefono;
	}

	public void setVrTelefono(String vrTelefono) {
		this.vrTelefono = vrTelefono;
	}

}
