package com.edalac.modelo.dto;

/**
 * TbTipopersona generated by hbm2java
 */
public class TbTipopersona implements java.io.Serializable {

	private static final long serialVersionUID = -7633809551200083990L;
	private long nbIdtipopersona;
	private String vrDescripcion;

	public TbTipopersona() {
	}

	public TbTipopersona(long nbIdtipopersona, String vrDescripcion) {
		this.nbIdtipopersona = nbIdtipopersona;
		this.vrDescripcion = vrDescripcion;
	}

	public long getNbIdtipopersona() {
		return this.nbIdtipopersona;
	}

	public void setNbIdtipopersona(long nbIdtipopersona) {
		this.nbIdtipopersona = nbIdtipopersona;
	}

	public String getVrDescripcion() {
		return this.vrDescripcion;
	}

	public void setVrDescripcion(String vrDescripcion) {
		this.vrDescripcion = vrDescripcion;
	}
}
