package com.edalac.modelo.dto;

/**
 * TbUsuario generated by hbm2java
 */
public class TbUsuario implements java.io.Serializable {

	private static final long serialVersionUID = 8089558491971719715L;
	private long nbIdusuario;
	private TbRol tbRol;
	private TbEmpresa tbEmpresa;
	private String vrUsuario;
	private String vrPasswd;

	public TbUsuario() {
	}

	public TbUsuario(long nbIdusuario) {
		this.nbIdusuario = nbIdusuario;
	}

	public TbUsuario(long nbIdusuario, TbRol tbRol, TbEmpresa tbEmpresa, String vrUsuario, String vrPasswd) {
		this.nbIdusuario = nbIdusuario;
		this.tbRol = tbRol;
		this.tbEmpresa = tbEmpresa;
		this.vrUsuario = vrUsuario;
		this.vrPasswd = vrPasswd;
	}

	public long getNbIdusuario() {
		return this.nbIdusuario;
	}

	public void setNbIdusuario(long nbIdusuario) {
		this.nbIdusuario = nbIdusuario;
	}

	public TbRol getTbRol() {
		return this.tbRol;
	}

	public void setTbRol(TbRol tbRol) {
		this.tbRol = tbRol;
	}

	public TbEmpresa getTbEmpresa() {
		return this.tbEmpresa;
	}

	public void setTbEmpresa(TbEmpresa tbEmpresa) {
		this.tbEmpresa = tbEmpresa;
	}

	public String getVrUsuario() {
		return this.vrUsuario;
	}

	public void setVrUsuario(String vrUsuario) {
		this.vrUsuario = vrUsuario;
	}

	public String getVrPasswd() {
		return this.vrPasswd;
	}

	public void setVrPasswd(String vrPasswd) {
		this.vrPasswd = vrPasswd;
	}

}
